insert into Region (distrito_nombre, region, num_region) values ('Melipilla', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('La Cisterna', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('La Granja', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Bellavista', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('AricayParinacota', 'Arica', '15');
insert into Region (distrito_nombre, region, num_region) values ('BioBio', 'Araucania', '9');
insert into Region (distrito_nombre, region, num_region) values ('Macul', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('La Portada', 'Antofagasta', '2');
insert into Region (distrito_nombre, region, num_region) values ('Alto Hospicio', 'Tarapaca', '1');
insert into Region (distrito_nombre, region, num_region) values ('La Portada', 'Libertador B.O.', '6');
insert into Region (distrito_nombre, region, num_region) values ('Colina', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Cerro Tarapaca', 'Tarapaca', '1');
insert into Region (distrito_nombre, region, num_region) values ('Cavancha Iquique', 'Tarapaca', '1');
insert into Region (distrito_nombre, region, num_region) values ('Santiago Centro', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Peñañolen', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Providencia', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Conchali', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Copayapu', 'Atacama', '3');
insert into Region (distrito_nombre, region, num_region) values ('Coloso Antofagasta', 'Antofagasta', '2');
insert into Region (distrito_nombre, region, num_region) values ('Curico', 'Maule', '7');
insert into Region (distrito_nombre, region, num_region) values ('Chiloe', 'Los Lagos', '10');
insert into Region (distrito_nombre, region, num_region) values ('Arica', 'Arica', '15');
insert into Region (distrito_nombre, region, num_region) values ('Apoquindo', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Choapa', 'Coquimbo', '4');
insert into Region (distrito_nombre, region, num_region) values ('El Bosque', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Jose Francisco Vergara', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('Linares', 'Maule', '7');
insert into Region (distrito_nombre, region, num_region) values ('Maipu Nuevo Extremo', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Mapurayen', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Marga Marga', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('Michimalonco', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('Nahuelbuta', 'BioBio', '8');
insert into Region (distrito_nombre, region, num_region) values ('Ñielol', 'Araucania', '9');
insert into Region (distrito_nombre, region, num_region) values ('O higgins', 'Libertador B.O.', '6');
insert into Region (distrito_nombre, region, num_region) values ('Pedro de Valdivia', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Viña del Mar', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('Villa Alemana', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('Valparaiso', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('Valle del Maipo', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Talcahuano', 'BioBio', '8');
insert into Region (distrito_nombre, region, num_region) values ('Talca', 'Maule', '7');
insert into Region (distrito_nombre, region, num_region) values ('San Joaquin', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Santa Rosa', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('San Bernardo', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('San Felipe', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('San Antonio', 'Valparaiso', '5');
insert into Region (distrito_nombre, region, num_region) values ('Quilicura', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Quilamapu', 'Metropolitana', '13');
insert into Region (distrito_nombre, region, num_region) values ('Puente Alto Poniente', 'Metropolitana', '13');
